# Generated by Django 5.0.6 on 2024-06-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Institue", models.CharField(max_length=100)),
                ("Branch", models.CharField(max_length=100)),
                ("Quota", models.CharField(max_length=100)),
                ("Seat_Type", models.CharField(max_length=100)),
                ("Opening_Rank", models.IntegerField()),
                ("Closing_Rank", models.IntegerField()),
                ("Year", models.IntegerField()),
                ("Round", models.IntegerField()),
            ],
        ),
    ]
